# XGBoost on PySpark - 二分类（信用卡欺诈检测）
分布式数据处理 → 特征工程 → 分布式训练 → 评估 → 预测

In [1]:
import os
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("XGBoost-Binary-Classification") \
    .master("spark://spark-master:7077") \
    .config("spark.executor.memory", "2g") \
    .config("spark.executor.cores", "1") \
    .config("spark.driver.memory", "2g") \
    .config("spark.task.cpus", "1") \
    .config("spark.sql.shuffle.partitions", "4") \
    .getOrCreate()

spark

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/06/20 13:34:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)
n_samples = 100000
n_features = 28

# 生成合成特征
X = np.random.randn(n_samples, n_features)
logits = -3 + 2 * X[:, 0] + 1.5 * X[:, 1] - X[:, 2] + 0.5 * X[:, 3]
probs = 1 / (1 + np.exp(-logits))
y = (probs > 0.5).astype(int)

# 添加少量噪声
flip_idx = np.random.choice(n_samples, size=int(n_samples * 0.01), replace=False)
y[flip_idx] = 1 - y[flip_idx]

print(f"Total samples: {n_samples}")
print(f"Positive (fraud): {y.sum()} ({y.mean()*100:.2f}%)")
print(f"Negative (normal): {(1-y).sum()} ({(1-y.mean())*100:.2f}%)")

# 构建DataFrame
columns = ["Time"] + [f"V{i}" for i in range(1, n_features+1)] + ["Amount", "Class"]
data = np.column_stack([
    np.arange(n_samples),
    X,
    np.abs(np.random.randn(n_samples) * 100 + 50),
    y
])

df_pd = pd.DataFrame(data, columns=columns)
df_pd["Class"] = df_pd["Class"].astype(int)

# 保存CSV
data_dir = "/home/feynman/work/data"
os.makedirs(data_dir, exist_ok=True)
csv_path = os.path.join(data_dir, "creditcard.csv")
df_pd.to_csv(csv_path, index=False)
print(f"Saved to {csv_path}")
print(f"File size: {os.path.getsize(csv_path) / 1024 / 1024:.2f} MB")
df_pd.head()

Total samples: 100000
Positive (fraud): 14464 (14.46%)
Negative (normal): 85536 (85.54%)
Saved to /home/feynman/work/data/creditcard.csv
File size: 55.12 MB

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,...,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,79.534575,0
1,1.0,-0.600639,-0.291694,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,...,0.343618,-1.763040,0.324084,-0.385082,-0.676922,0.611676,1.031000,0.931280,78.643578,0
2,2.0,-0.839218,-0.309212,0.331263,0.975545,-0.479174,-0.185659,-1.106335,-1.196207,0.812526,...,0.087047,-0.299007,0.091761,-1.987569,-0.219672,0.357113,1.477894,-0.518270,31.221224,0
3,3.0,-0.808494,-0.501757,0.915402,0.328751,-0.529760,0.513267,0.097078,0.968645,-0.702053,...,-0.161286,0.404051,1.886186,0.174578,0.257550,-0.074446,-1.918771,-0.026514,91.888621,0
4,4.0,0.060230,2.463242,-0.192361,0.301547,-0.034712,-1.168678,1.142823,0.751933,0.791032,...,-1.062304,0.473592,-0.919424,1.549934,-0.783253,-0.322062,0.813517,-1.230864,63.332089,1

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,...,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,79.534575,0
1,1.0,-0.600639,-0.291694,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,...,0.343618,-1.763040,0.324084,-0.385082,-0.676922,0.611676,1.031000,0.931280,78.643578,0
2,2.0,-0.839218,-0.309212,0.331263,0.975545,-0.479174,-0.185659,-1.106335,-1.196207,0.812526,...,0.087047,-0.299007,0.091761,-1.987569,-0.219672,0.357113,1.477894,-0.518270,31.221224,0
3,3.0,-0.808494,-0.501757,0.915402,0.328751,-0.529760,0.513267,0.097078,0.968645,-0.702053,...,-0.161286,0.404051,1.886186,0.174578,0.257550,-0.074446,-1.918771,-0.026514,91.888621,0
4,4.0,0.060230,2.463242,-0.192361,0.301547,-0.034712,-1.168678,1.142823,0.751933,0.791032,...,-1.062304,0.473592,-0.919424,1.549934,-0.783253,-0.322062,0.813517,-1.230864,63.332089,1

## 1. 分布式数据加载与探索

In [3]:
# 用Spark分布式读取CSV
df = spark.read.csv(
    f"file://{csv_path}",
    header=True,
    inferSchema=True
)

print(f"分区数: {df.rdd.getNumPartitions()}")
print(f"总行数: {df.count()}")
print(f"总列数: {len(df.columns)}")
df.printSchema()

分区数: 2
总行数: 100000
总列数: 31
root
 |-- Time: double (nullable = true)
 |-- V1: double (nullable = true)
 |-- V2: double (nullable = true)
 |-- V3: double (nullable = true)
 |-- V4: double (nullable = true)
 |-- V5: double (nullable = true)
 |-- V6: double (nullable = true)
 |-- V7: double (nullable = true)
 |-- V8: double (nullable = true)
 |-- V9: double (nullable = true)
 |-- V10: double (nullable = true)
 |-- V11: double (nullable = true)
 |-- V12: double (nullable = true)
 |-- V13: double (nullable = true)
 |-- V14: double (nullable = true)
 |-- V15: double (nullable = true)
 |-- V16: double (nullable = true)
 |-- V17: double (nullable = true)
 |-- V18: double (nullable = true)
 |-- V19: double (nullable = true)
 |-- V20: double (nullable = true)
 |-- V21: double (nullable = true)
 |-- V22: double (nullable = true)
 |-- V23: double (nullable = true)
 |-- V24: double (nullable = true)
 |-- V25: double (nullable = true)
 |-- V26: double (nullable = true)
 |-- V27: double (nullable = true)
 |-- V28: double (nullable = true)
 |-- Amount: double (nullable = true)
 |-- Class: integer (nullable = true)

分区数: 2

总行数: 100000
总列数: 31
root
 |-- Time: double (nullable = true)
 |-- V1: double (nullable = true)
 |-- V2: double (nullable = true)
 |-- V3: double (nullable = true)
 |-- V4: double (nullable = true)
 |-- V5: double (nullable = true)
 |-- V6: double (nullable = true)
 |-- V7: double (nullable = true)
 |-- V8: double (nullable = true)
 |-- V9: double (nullable = true)
 |-- V10: double (nullable = true)
 |-- V11: double (nullable = true)
 |-- V12: double (nullable = true)
 |-- V13: double (nullable = true)
 |-- V14: double (nullable = true)
 |-- V15: double (nullable = true)
 |-- V16: double (nullable = true)
 |-- V17: double (nullable = true)
 |-- V18: double (nullable = true)
 |-- V19: double (nullable = true)
 |-- V20: double (nullable = true)
 |-- V21: double (nullable = true)
 |-- V22: double (nullable = true)
 |-- V23: double (nullable = true)
 |-- V24: double (nullable = true)
 |-- V25: double (nullable = true)
 |-- V26: double (nullable = true)
 |-- V27: double (nullable = true)
 |-- V28: double (nullable = true)
 |-- Amount: double (nullable = true)
 |-- Class: integer (nullable = true)

In [4]:
from pyspark.sql import functions as F

# 正负样本分布
df.groupBy("Class").count().show()

# 描述性统计
numeric_cols = [f"V{i}" for i in range(1, 29)] + ["Amount"]
df.select(numeric_cols).describe().show()
df.show(2)

+-----+-----+
|Class|count|
+-----+-----+
|    0|85536|
|    1|14464|
+-----+-----+

26/06/20 13:35:10 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|summary|                  V1|                 V2|                  V3|                  V4|                  V5|                  V6|                  V7|                  V8|                  V9|                 V10|                 V11|                 V12|                 V13|                 V14|                 V15|                 V16|                 V17|                 V18|                 V19|                 V20|                 V21|                 V22|                 V23|                 V24|                 V25|                 V26|                 V27|                 V28|              Amount|
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|  count|              100000|             100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|
|   mean|2.892796994636758E-4|7.95460170048978E-4|-0.00255178987544...|3.111537170327640...|6.000969707840545E-4|0.002383257667098...|-2.09890259261849...|-0.00354187979184...|-6.83439984132001...|-0.00275435136453...|1.632808945088453...|-9.43477311196203...|-0.00279529168159...|2.642667735940881...|0.001292273663292...|9.738012571986662E-4|-0.00240239215891...|-0.00477305103822...|-0.00313651872592...|-0.00208130841653...|3.395238987556115...|-0.00348472744971...|0.001702591273326...|-0.00401441937133...|-0.00207957453327...|0.002959739551674...|-0.00136860085414...|0.003832665050028...|   89.71396963455045|
| stddev|  0.9983109590173403| 1.0028066470762995|  1.0035028370887287|  1.0034084466961812|  1.0003423228922672|  1.0000820888788313|  1.0041124858271078|   1.000144938142847|  0.9992234736990309|  0.9993223475690917|  0.9999701916345075|  0.9991944124213415|  0.9996869911131737|  1.0035098418864066|  1.0001135120167846|  1.0011823991678925|   0.998817238428291|  0.9990989250756594|  0.9996901467070785|  0.9981452507591977|   1.000104282163783|  0.9993416194753165|  0.9978874159505419|   1.001415857666527|  1.0009918704910294|  1.0045014863494506|  1.0004696638013206|  0.9985044409826802|   66.73260112184047|
|    min|  -4.415183744580719| -4.319464832285259|  -4.404213960877153|  -4.368673045782893|  -4.337679442780434| -4.4656038635288775|  -4.320054096622606| -4.1577338773991315|  -4.534014065999817|  -4.448303583887974|  -4.596948183086173|  -4.431854301496356|   -3.94902687430091|   -4.62525848776203|  -4.484079232363088| -4.5134692153598674|  -4.230120636833231|  -4.520892434895728|   -4.98014593114449|  -4.644418774315494|  -4.829436008511157|  -4.061669707455677| -3.9767185132102143|  -4.435060898724634|  -4.280224577971017|  -4.066894021062747|  -4.295390984068005| -3.9633795881222453|5.814414023177505E-4|
|    max|   4.427568977877988|  4.827622729327414|   4.098078356862284|   4.536172900474708|   4.065265833936367|  4.9842150330074935|   4.386935356153178|  3.9802802491519005|   4.610534214005424|   4.678949100376724|  4.3983260226416165|   4.659489533146858|  4.3374241505061395|   4.289265213961174|   4.368631257159261|  4.5958282968981505|   4.185726191317748|    4.01640299479997|   4.059371877114808|   4.365279199570614|   4.215213592967612|    4.28989278208242|   4.352342525620309|   4.562114723614891|   4.271014628109549|   4.616383922771782|   4.295232057267458|   4.156720556709468|  480.65121600601026|
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
|Time|                V1|                  V2|                 V3|                V4|                  V5|                  V6|                V7|                 V8|                 V9|                V10|                 V11|                 V12|                V13|               V14|                 V15|                V16|                V17|                V18|                V19|                V20|               V21|                 V22|                V23|                 V24|                V25|                V26|                V27|                V28|           Amount|Class|
+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
| 0.0|0.4967141530112327|-0.13826430117118466| 0.6476885381006925|1.5230298564080254|-0.23415337472333597|-0.23413695694918055|1.5792128155073915| 0.7674347291529088|-0.4694743859349521| 0.5425600435859647|-0.46341769281246226|-0.46572975357025687|0.24196227156603412|-1.913280244657798| -1.7249178325130328|-0.5622875292409727|-1.0128311203344238| 0.3142473325952739|-0.9080240755212109|-1.4123037013352915| 1.465648768921554|-0.22577630048653566|0.06752820468792384| -1.4247481862134568|-0.5443827245251827|0.11092258970986608|-1.1509935774223028|0.37569801834567196|79.53457506617659|    0|
| 1.0|-0.600638689918805| -0.2916937497932768|-0.6017066122293969|1.8522781845089378|-0.01349722473793...| -1.0577109289559004| 0.822544912103189|-1.2208436499710222| 0.2088635950047554|-1.9596701238797756| -1.3281860488984305| 0.19686123586912352| 0.7384665799954104|0.1713682811899705|-0.11564828238824053|-0.3011036955892888|-1.4785219903674274|-0.7198442083947086|-0.4606387709597875| 1.0571222262189157|0.3436182895684614|  -1.763040155362734|  0.324083969394795|-0.38508228041631654|-0.6769220003059587| 0.6116762888408679|  1.030999522495951| 0.9312801191161986|78.64357797014094|    0|
+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
only showing top 2 rows

+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|summary|                  V1|                 V2|                  V3|                  V4|                  V5|                  V6|                  V7|                  V8|                  V9|                 V10|                 V11|                 V12|                 V13|                 V14|                 V15|                 V16|                 V17|                 V18|                 V19|                 V20|                 V21|                 V22|                 V23|                 V24|                 V25|                 V26|                 V27|                 V28|              Amount|
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
|  count|              100000|             100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|              100000|
|   mean|2.892796994636758E-4|7.95460170048978E-4|-0.00255178987544...|3.111537170327640...|6.000969707840545E-4|0.002383257667098...|-2.09890259261849...|-0.00354187979184...|-6.83439984132001...|-0.00275435136453...|1.632808945088453...|-9.43477311196203...|-0.00279529168159...|2.642667735940881...|0.001292273663292...|9.738012571986662E-4|-0.00240239215891...|-0.00477305103822...|-0.00313651872592...|-0.00208130841653...|3.395238987556115...|-0.00348472744971...|0.001702591273326...|-0.00401441937133...|-0.00207957453327...|0.002959739551674...|-0.00136860085414...|0.003832665050028...|   89.71396963455045|
| stddev|  0.9983109590173403| 1.0028066470762995|  1.0035028370887287|  1.0034084466961812|  1.0003423228922672|  1.0000820888788313|  1.0041124858271078|   1.000144938142847|  0.9992234736990309|  0.9993223475690917|  0.9999701916345075|  0.9991944124213415|  0.9996869911131737|  1.0035098418864066|  1.0001135120167846|  1.0011823991678925|   0.998817238428291|  0.9990989250756594|  0.9996901467070785|  0.9981452507591977|   1.000104282163783|  0.9993416194753165|  0.9978874159505419|   1.001415857666527|  1.0009918704910294|  1.0045014863494506|  1.0004696638013206|  0.9985044409826802|   66.73260112184047|
|    min|  -4.415183744580719| -4.319464832285259|  -4.404213960877153|  -4.368673045782893|  -4.337679442780434| -4.4656038635288775|  -4.320054096622606| -4.1577338773991315|  -4.534014065999817|  -4.448303583887974|  -4.596948183086173|  -4.431854301496356|   -3.94902687430091|   -4.62525848776203|  -4.484079232363088| -4.5134692153598674|  -4.230120636833231|  -4.520892434895728|   -4.98014593114449|  -4.644418774315494|  -4.829436008511157|  -4.061669707455677| -3.9767185132102143|  -4.435060898724634|  -4.280224577971017|  -4.066894021062747|  -4.295390984068005| -3.9633795881222453|5.814414023177505E-4|
|    max|   4.427568977877988|  4.827622729327414|   4.098078356862284|   4.536172900474708|   4.065265833936367|  4.9842150330074935|   4.386935356153178|  3.9802802491519005|   4.610534214005424|   4.678949100376724|  4.3983260226416165|   4.659489533146858|  4.3374241505061395|   4.289265213961174|   4.368631257159261|  4.5958282968981505|   4.185726191317748|    4.01640299479997|   4.059371877114808|   4.365279199570614|   4.215213592967612|    4.28989278208242|   4.352342525620309|   4.562114723614891|   4.271014628109549|   4.616383922771782|   4.295232057267458|   4.156720556709468|  480.65121600601026|
+-------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
|Time|                V1|                  V2|                 V3|                V4|                  V5|                  V6|                V7|                 V8|                 V9|                V10|                 V11|                 V12|                V13|               V14|                 V15|                V16|                V17|                V18|                V19|                V20|               V21|                 V22|                V23|                 V24|                V25|                V26|                V27|                V28|           Amount|Class|
+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
| 0.0|0.4967141530112327|-0.13826430117118466| 0.6476885381006925|1.5230298564080254|-0.23415337472333597|-0.23413695694918055|1.5792128155073915| 0.7674347291529088|-0.4694743859349521| 0.5425600435859647|-0.46341769281246226|-0.46572975357025687|0.24196227156603412|-1.913280244657798| -1.7249178325130328|-0.5622875292409727|-1.0128311203344238| 0.3142473325952739|-0.9080240755212109|-1.4123037013352915| 1.465648768921554|-0.22577630048653566|0.06752820468792384| -1.4247481862134568|-0.5443827245251827|0.11092258970986608|-1.1509935774223028|0.37569801834567196|79.53457506617659|    0|
| 1.0|-0.600638689918805| -0.2916937497932768|-0.6017066122293969|1.8522781845089378|-0.01349722473793...| -1.0577109289559004| 0.822544912103189|-1.2208436499710222| 0.2088635950047554|-1.9596701238797756| -1.3281860488984305| 0.19686123586912352| 0.7384665799954104|0.1713682811899705|-0.11564828238824053|-0.3011036955892888|-1.4785219903674274|-0.7198442083947086|-0.4606387709597875| 1.0571222262189157|0.3436182895684614|  -1.763040155362734|  0.324083969394795|-0.38508228041631654|-0.6769220003059587| 0.6116762888408679|  1.030999522495951| 0.9312801191161986|78.64357797014094|    0|
+----+------------------+--------------------+-------------------+------------------+--------------------+--------------------+------------------+-------------------+-------------------+-------------------+--------------------+--------------------+-------------------+------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------+--------------------+-------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----+
only showing top 2 rows

## 2. 特征工程

In [5]:
from pyspark.ml.feature import VectorAssembler

# 特征列
feature_cols = [f"V{i}" for i in range(1, 29)] + ["Amount"]

# 检查 null
null_check = df.select([F.count(F.when(F.col(c).isNull(), c)).alias(c) for c in feature_cols])
print("Null counts per feature:")
null_check.show()

# 向量化（XGBoost 是树模型，不需要标准化）
assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features",
    handleInvalid="skip"
)

df_transformed = assembler.transform(df).select("features", "Class")
print("预处理完成！")
df_transformed.show(5, truncate=False)

Null counts per feature:

+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+------+
| V1| V2| V3| V4| V5| V6| V7| V8| V9|V10|V11|V12|V13|V14|V15|V16|V17|V18|V19|V20|V21|V22|V23|V24|V25|V26|V27|V28|Amount|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+------+
|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|     0|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+------+

预处理完成！
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |Class|
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|[0.4967141530112327,-0.13826430117118466,0.6476885381006925,1.5230298564080254,-0.23415337472333597,-0.23413695694918055,1.5792128155073915,0.7674347291529088,-0.4694743859349521,0.5425600435859647,-0.46341769281246226,-0.46572975357025687,0.24196227156603412,-1.913280244657798,-1.7249178325130328,-0.5622875292409727,-1.0128311203344238,0.3142473325952739,-0.9080240755212109,-1.4123037013352915,1.465648768921554,-0.22577630048653566,0.06752820468792384,-1.4247481862134568,-0.5443827245251827,0.11092258970986608,-1.1509935774223028,0.37569801834567196,79.53457506617659]      |0    |
|[-0.600638689918805,-0.2916937497932768,-0.6017066122293969,1.8522781845089378,-0.013497224737933921,-1.0577109289559004,0.822544912103189,-1.2208436499710222,0.2088635950047554,-1.9596701238797756,-1.3281860488984305,0.19686123586912352,0.7384665799954104,0.1713682811899705,-0.11564828238824053,-0.3011036955892888,-1.4785219903674274,-0.7198442083947086,-0.4606387709597875,1.0571222262189157,0.3436182895684614,-1.763040155362734,0.324083969394795,-0.38508228041631654,-0.6769220003059587,0.6116762888408679,1.030999522495951,0.9312801191161986,78.64357797014094]              |0    |
|[-0.8392175232226385,-0.3092123758512146,0.33126343140356396,0.9755451271223592,-0.47917423784528995,-0.18565897666381712,-1.1063349740060282,-1.1962066240806708,0.812525822394198,1.356240028570823,-0.07201012158033385,1.0035328978920242,0.36163602504763415,-0.6451197546051243,0.36139560550841393,1.5380365664659692,-0.03582603910995154,1.5646436558140062,-2.6197451040897444,0.8219025043752238,0.08704706823817122,-0.29900735046586746,0.0917607765355023,-1.9875689146008928,-0.21967188783751193,0.3571125715117464,1.477894044741516,-0.5182702182736474,31.221223870416498]        |0    |
|[-0.8084936028931876,-0.5017570435845365,0.9154021177020741,0.32875110965968446,-0.5297602037670388,0.5132674331133561,0.09707754934804039,0.9686449905328892,-0.7020530938773524,-0.3276621465977682,-0.39210815313215763,-1.4635149481321186,0.29612027706457605,0.26105527217988933,0.00511345664246089,-0.23458713337514692,-1.4153707420504142,-0.42064532276535904,-0.3427145165267695,-0.8022772692216189,-0.16128571166600914,0.4040508568145384,1.8861859012105302,0.17457781283183896,0.25755039072276437,-0.07444591576616721,-1.9187712152990415,-0.026513875449216878,91.88862090690301]|0    |
|[0.06023020994102644,2.463242112485286,-0.19236096478112252,0.30154734233361247,-0.03471176970524331,-1.168678037619532,1.1428228145150205,0.7519330326867741,0.7910319470430469,-0.9093874547947389,1.4027943109360992,-1.4018510627922809,0.5868570938002703,2.1904556258099785,-0.9905363251306883,-0.5662977296027719,0.09965136508764122,-0.5034756541161992,-1.5506634310661327,0.06856297480602733,-1.0623037137261049,0.4735924306351816,-0.9194242342338032,1.5499344050175394,-0.7832532923362371,-0.3220615162056756,0.8135172173696698,-1.2308643164339552,63.33208900157461]            |1    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
only showing top 5 rows

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |Class|
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|[0.4967141530112327,-0.13826430117118466,0.6476885381006925,1.5230298564080254,-0.23415337472333597,-0.23413695694918055,1.5792128155073915,0.7674347291529088,-0.4694743859349521,0.5425600435859647,-0.46341769281246226,-0.46572975357025687,0.24196227156603412,-1.913280244657798,-1.7249178325130328,-0.5622875292409727,-1.0128311203344238,0.3142473325952739,-0.9080240755212109,-1.4123037013352915,1.465648768921554,-0.22577630048653566,0.06752820468792384,-1.4247481862134568,-0.5443827245251827,0.11092258970986608,-1.1509935774223028,0.37569801834567196,79.53457506617659]      |0    |
|[-0.600638689918805,-0.2916937497932768,-0.6017066122293969,1.8522781845089378,-0.013497224737933921,-1.0577109289559004,0.822544912103189,-1.2208436499710222,0.2088635950047554,-1.9596701238797756,-1.3281860488984305,0.19686123586912352,0.7384665799954104,0.1713682811899705,-0.11564828238824053,-0.3011036955892888,-1.4785219903674274,-0.7198442083947086,-0.4606387709597875,1.0571222262189157,0.3436182895684614,-1.763040155362734,0.324083969394795,-0.38508228041631654,-0.6769220003059587,0.6116762888408679,1.030999522495951,0.9312801191161986,78.64357797014094]              |0    |
|[-0.8392175232226385,-0.3092123758512146,0.33126343140356396,0.9755451271223592,-0.47917423784528995,-0.18565897666381712,-1.1063349740060282,-1.1962066240806708,0.812525822394198,1.356240028570823,-0.07201012158033385,1.0035328978920242,0.36163602504763415,-0.6451197546051243,0.36139560550841393,1.5380365664659692,-0.03582603910995154,1.5646436558140062,-2.6197451040897444,0.8219025043752238,0.08704706823817122,-0.29900735046586746,0.0917607765355023,-1.9875689146008928,-0.21967188783751193,0.3571125715117464,1.477894044741516,-0.5182702182736474,31.221223870416498]        |0    |
|[-0.8084936028931876,-0.5017570435845365,0.9154021177020741,0.32875110965968446,-0.5297602037670388,0.5132674331133561,0.09707754934804039,0.9686449905328892,-0.7020530938773524,-0.3276621465977682,-0.39210815313215763,-1.4635149481321186,0.29612027706457605,0.26105527217988933,0.00511345664246089,-0.23458713337514692,-1.4153707420504142,-0.42064532276535904,-0.3427145165267695,-0.8022772692216189,-0.16128571166600914,0.4040508568145384,1.8861859012105302,0.17457781283183896,0.25755039072276437,-0.07444591576616721,-1.9187712152990415,-0.026513875449216878,91.88862090690301]|0    |
|[0.06023020994102644,2.463242112485286,-0.19236096478112252,0.30154734233361247,-0.03471176970524331,-1.168678037619532,1.1428228145150205,0.7519330326867741,0.7910319470430469,-0.9093874547947389,1.4027943109360992,-1.4018510627922809,0.5868570938002703,2.1904556258099785,-0.9905363251306883,-0.5662977296027719,0.09965136508764122,-0.5034756541161992,-1.5506634310661327,0.06856297480602733,-1.0623037137261049,0.4735924306351816,-0.9194242342338032,1.5499344050175394,-0.7832532923362371,-0.3220615162056756,0.8135172173696698,-1.2308643164339552,63.33208900157461]            |1    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
only showing top 5 rows

In [6]:
# 训练/测试集划分
train_df, test_df = df_transformed.randomSplit([0.8, 0.2], seed=42)

# 重新分区并缓存
train_df = train_df.repartition(2).cache()
test_df = test_df.cache()

# 触发缓存并统计
train_count = train_df.count()
test_count = test_df.count()

train_pos = train_df.filter(F.col("Class") == 1).count()
train_neg = train_df.filter(F.col("Class") == 0).count()
test_pos = test_df.filter(F.col("Class") == 1).count()
test_neg = test_df.filter(F.col("Class") == 0).count()

print(f"训练集: {train_count} (正:{train_pos}, 负:{train_neg})")
print(f"测试集: {test_count} (正:{test_pos}, 负:{test_neg})")

# 验证各分区不为空
partitions = train_df.rdd.glom().map(len).collect()
print(f"训练集各分区行数: {partitions}")

训练集: 80009 (正:11499, 负:68510)
测试集: 19991 (正:2965, 负:17026)

[Stage 45:>                                                         (0 + 2) / 2]

训练集各分区行数: [40004, 40005]

训练集各分区行数: [40004, 40005]

## 3. 分布式 XGBoost 训练

In [7]:
from xgboost.spark import SparkXGBClassifier
import time

# 配置分布式XGBoost分类器
xgb_classifier = SparkXGBClassifier(
    features_col="features",
    label_col="Class",
    num_workers=2,
    n_estimators=50,
    max_depth=6,
    learning_rate=0.1,
    eval_metric="auc",
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    scale_pos_weight=3.0,
    missing=0.0,
    verbosity=1,
)

print("开始分布式训练...")
start_time = time.time()

xgb_model = xgb_classifier.fit(train_df)

train_time = time.time() - start_time
print(f"训练完成！耗时: {train_time:.2f} 秒")

/usr/local/lib/python3.8/dist-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

开始分布式训练...

2026-06-20 13:35:21,232 INFO XGBoost-PySpark: _fit Running xgboost-2.1.4 on 2 workers with
	booster params: {'objective': 'binary:logistic', 'colsample_bytree': 0.8, 'device': 'cpu', 'eval_metric': 'auc', 'learning_rate': 0.1, 'max_depth': 6, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'scale_pos_weight': 3.0, 'subsample': 0.8, 'verbosity': 1, 'nthread': 1}
	train_call_kwargs_params: {'verbose_eval': True, 'num_boost_round': 50}
	dmatrix_kwargs: {'nthread': 1, 'missing': 0.0}
2026-06-20 13:35:25,972 INFO XGBoost-PySpark: _fit Finished xgboost training!

训练完成！耗时: 5.23 秒

2026-06-20 13:34:21,394 INFO XGBoost-PySpark: _fit Finished xgboost training!

训练完成！耗时: 4.93 秒

## 4. 模型评估

In [8]:
# 分布式预测
predictions = xgb_model.transform(test_df)
predictions.select("features", "Class", "rawPrediction", "probability", "prediction").show(10, truncate=False)

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------------------------------------+-----------------------------------------+----------+
|features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |Class|rawPrediction                           |probability                              |prediction|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------------------------------------+-----------------------------------------+----------+
|[-3.940590407826172,0.479276238075949,0.09205357182500225,1.1337478329859554,-1.5864339357535537,0.5130127712124459,-0.6697558287149146,0.3127512917276175,-0.5759874757246692,-1.1875330269599602,-0.6854395087812645,-2.658928648901826,0.07079575353202222,-0.5807279029239205,0.5169643379065028,-0.42663250545419096,0.051102682819985416,3.0050666800340715,-0.5373956035431947,0.34223661738682226,0.7203700535856361,2.5162034710805496,-0.7618562104255621,0.5338231966796618,-1.9752096711428844,0.5550431174659957,1.4515759576835257,0.22045097666002755,195.13100077776085]      |0    |[2.912172794342041,-2.912172794342041]  |[0.9484449028968811,0.0515550896525383]  |0.0       |
|[-3.728269560330043,2.41460777897088,-1.0509243135027417,-1.3317951051150203,0.6671351785568608,1.3634854747580287,-0.8585806704306794,0.003340314067014376,-0.9029549469336193,-0.5109242747065127,-0.5437343374359822,1.9150874270766212,0.12731927237349933,0.5910199730487895,-0.4287508879072299,-0.14180749694968955,-0.30022866382962127,1.7076638082214077,-1.0937106535329715,0.8017327462830125,-1.3457846935790612,0.1875968196666742,0.11149182756567311,-0.2262353504525539,-0.23369643259079825,-1.3912822226059782,-1.2185151446283276,-0.15604705445257522,143.50165193986834]|0    |[2.194976329803467,-2.194976329803467]  |[0.8997974991798401,0.1002025231719017]  |0.0       |
|[-3.660516168698249,0.6800049431088081,-0.7541844041573862,1.2539169131617767,0.43408140194948047,-0.9699207046691232,-1.3341739591235409,-0.6665459770395418,-1.548886214049261,-0.11232432199385756,-0.1424331546532898,-0.05286971867732431,-0.7564919133645152,0.2680512160812406,-0.19064518928449473,1.4967179579317387,0.855985355586111,0.618637634926327,-1.3667491853557658,-1.293986100404377,-1.1350123596513042,0.4808782656248955,-1.102077185345917,-0.5428907561172255,-0.0046319244375600446,2.00364163767765,-0.032993575569049374,-2.3172894907016257,137.24959542584372]  |0    |[2.3989741802215576,-2.3989741802215576]|[0.9167490601539612,0.08325095474720001] |0.0       |
|[-3.582412715187922,-1.4967275749235536,1.0440576488875921,0.3609006004190888,-0.025297560392461248,-1.2606969419773795,0.8220582186545988,1.5050603590634983,-0.7260726625262603,0.8478951788488238,-0.8582293187760583,-0.22556741337263003,-0.4082897065365772,0.20778325976606307,0.9182576625688121,-1.4643022836383546,0.7595336039266796,-0.4258115388586152,-2.5619390851555015,-0.6946565966678846,-0.6831031566240849,-3.2139007449276664,0.3545568977549094,0.0444769982475154,-0.10956074353122489,0.9564166024489215,-0.6966034611742463,-0.02303794283048265,164.3379599755578] |0    |[2.8583455085754395,-2.8583455085754395]|[0.9457484483718872,0.054251525551080704]|0.0       |
|[-3.4397562707962526,0.05657286218398703,-0.09009944247076208,-0.3725421289222686,1.7923340796004403,1.2593400882167936,0.44501225310279224,-0.1629962892480489,1.174274359397773,-1.1561086222557073,-1.257147709848109,0.09328814553104976,-0.19878561051596852,-0.8115934028751276,0.42905043038221236,1.4146476765377776,0.6278270742855069,-0.880197914628682,-2.6504776165575925,2.047651009325819,1.009392885983719,0.3559873162882526,-1.828744386189634,0.534415181700703,1.2770144051656172,1.6632007187048772,0.5164505045000497,2.014497756741166,141.30631098504102]             |0    |[2.886815071105957,-2.886815071105957]  |[0.9471908211708069,0.052809201180934906]|0.0       |
|[-3.3701869536162024,0.9976933398190546,0.7219737402404522,1.0563454144265683,1.7844848094870949,-0.1726803177681978,-0.40993472997150565,1.5441205961979698,-1.3539318483564433,1.4773738532293799,0.02577965863891904,-0.7958656683271598,-1.1896311104880917,2.4538903251981203,0.9982591999741984,-2.2926713268950083,-0.6264056451463177,1.0378521673139172,-0.9643357230477118,-0.1647111811085972,0.19431013005052006,-0.7981762914652336,1.1136700167947389,0.10336069986783503,0.5397649942819858,-0.2811282978215669,0.9306454790327007,1.7278831952765574,14.4496923763446]        |1    |[3.1856236457824707,-3.1856236457824707]|[0.9602896571159363,0.03971032798290253] |0.0       |
|[-3.3291525433020452,0.7729675565903907,0.7775912878961889,0.9001157484130214,1.7783049706873053,-1.702341482642189,0.4821046062601836,-1.952720657219221,-0.8746762674575654,-0.6345793610849229,0.30865790490665285,-0.8598007528756292,-2.541615320684375,-0.24040350244060812,-0.4364961591377101,0.08030930971616078,0.13906015580538003,-1.5699011552312387,-0.5847056962875303,-0.4378161917169091,1.9633798213228446,0.5851324322485356,-0.8706838126141655,0.6566646544948449,0.7466881241222727,0.04085381805820367,-0.492882667892806,-0.546043968923039,2.0925521473659003]       |0    |[3.2165777683258057,-3.2165777683258057]|[0.961453378200531,0.038546618074178696] |0.0       |
|[-3.2733031449493133,0.7319055825545822,0.030760487553148197,-1.8240324882616887,-0.8038547089934193,-0.484876582805372,-0.3231629070671106,-0.8894310752350015,1.0796659405714302,-0.3188986344546407,-0.7219089647609226,-0.35240694629949043,0.018052780690810715,-1.281804124456936,0.4282240705728931,0.44365661822952734,0.2549941121771859,2.1523192790437484,1.8131905249138498,0.10295587882800679,-0.2548350738960422,-0.7025894541042406,0.5948109750192552,0.3270058365575239,-0.029072303428845214,0.4757863265556396,-0.5135866146580162,-0.34662411960560663,90.54554321573383]|0    |[3.6509294509887695,-3.6509294509887695]|[0.9746902585029602,0.025309763848781586]|0.0       |
|[-3.2210163559857135,0.39559883476294233,0.034271814200222225,-1.6808704592381203,0.3097267791360022,0.475751991831532,0.5896392313574,-2.651828063044949,1.3663894118544384,-0.7377367046848409,0.6865677467531761,0.741073780682286,-0.8766970856192929,0.6604599523515503,-0.3854932409123582,-2.0713771793381572,1.167741925527779,-0.7750449630162398,-0.8544934627380543,-0.4030658680367221,0.2722367253273881,-0.05727041082210227,0.5480669247071704,-1.339489366528659,-0.7423863704307346,-0.11599707232153356,1.8978872926587056,-0.11381253841375806,14.036004109574556]         |0    |[3.5130274295806885,-3.5130274295806885]|[0.9710561633110046,0.028943825513124466]|0.0       |
|[-3.2185385576296284,-0.7564869806685983,-0.055506757274753564,0.33905632239058164,1.3988657724284563,0.968975338916526,0.56243361101148,0.10770225514930279,0.7213943552925531,0.6032650549831643,-1.2909999772123755,1.6852438500810234,1.3965986986312786,0.8832806524761324,0.9183119490016238,-1.6421838530996,0.7785385974683898,0.9979201423214834,0.1530341133123275,-0.8201927631507077,-1.0554135210439528,-0.1956701324145459,0.5787218334412811,-0.1751359026918467,-0.0620134445382055,0.5502215547149195,-0.0674992399351975,-0.4350971085755016,146.84523508728023]            |0    |[3.864461660385132,-3.864461660385132]  |[0.9794566631317139,0.020543331280350685]|0.0       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------------------------------------+-----------------------------------------+----------+
only showing top 10 rows

In [9]:
from pyspark.ml.evaluation import BinaryClassificationEvaluator, MulticlassClassificationEvaluator

auc = BinaryClassificationEvaluator(
    labelCol="Class", rawPredictionCol="rawPrediction", metricName="areaUnderROC"
).evaluate(predictions)

pr_auc = BinaryClassificationEvaluator(
    labelCol="Class", rawPredictionCol="rawPrediction", metricName="areaUnderPR"
).evaluate(predictions)

accuracy = MulticlassClassificationEvaluator(
    labelCol="Class", predictionCol="prediction", metricName="accuracy"
).evaluate(predictions)

f1 = MulticlassClassificationEvaluator(
    labelCol="Class", predictionCol="prediction", metricName="f1"
).evaluate(predictions)

print("=" * 50)
print("模型评估结果")
print("=" * 50)
print(f"AUC (ROC):      {auc:.4f}")
print(f"AUC (PR):       {pr_auc:.4f}")
print(f"Accuracy:       {accuracy:.4f}")
print(f"F1 Score:       {f1:.4f}")

==================================================
模型评估结果
==================================================
AUC (ROC):      0.9717
AUC (PR):       0.9466
Accuracy:       0.9679
F1 Score:       0.9685

==================================================
模型评估结果
==================================================
AUC (ROC):      0.9717
AUC (PR):       0.9465
Accuracy:       0.9671
F1 Score:       0.9677

In [10]:
# 分布式计算混淆矩阵
cm = predictions.groupBy("Class", "prediction").count().orderBy("Class", "prediction")
cm_pd = cm.toPandas()

tp = cm_pd[(cm_pd["Class"] == 1) & (cm_pd["prediction"] == 1)]["count"].sum()
tn = cm_pd[(cm_pd["Class"] == 0) & (cm_pd["prediction"] == 0)]["count"].sum()
fp = cm_pd[(cm_pd["Class"] == 0) & (cm_pd["prediction"] == 1)]["count"].sum()
fn = cm_pd[(cm_pd["Class"] == 1) & (cm_pd["prediction"] == 0)]["count"].sum()

print("混淆矩阵:")
print(f"                预测负      预测正")
print(f"实际负        {int(tn):>8}    {int(fp):>8}")
print(f"实际正        {int(fn):>8}    {int(tp):>8}")

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0
print(f"\nPrecision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")

混淆矩阵:
                预测负      预测正
实际负           16576         450
实际正             191        2774

Precision: 0.8604
Recall:    0.9356

## 5. 模型预测（新数据）

In [11]:
import numpy as np
import pandas as pd

np.random.seed(123)
n_new = 5

new_X = np.random.randn(n_new, 28) * 0.5
new_amount = np.abs(np.random.randn(n_new) * 50 + 100)

new_data = np.column_stack([np.arange(n_new), new_X, new_amount, np.zeros(n_new)])
columns = ["Time"] + [f"V{i}" for i in range(1, 29)] + ["Amount", "Class"]
new_pd = pd.DataFrame(new_data, columns=columns)
new_pd["Class"] = new_pd["Class"].astype(int)

new_spark_df = spark.createDataFrame(new_pd)
new_transformed = assembler.transform(new_spark_df).select("features")

new_predictions = xgb_model.transform(new_transformed)

print("新数据预测结果:")
result = new_predictions.select("probability", "prediction").toPandas()
for i, row in result.iterrows():
    fraud_prob = row["probability"][1]
    pred_label = "欺诈" if row["prediction"] == 1 else "正常"
    print(f"样本{i+1}: 欺诈概率={fraud_prob:.4f}, 预测={pred_label}")

新数据预测结果:
样本1: 欺诈概率=0.0319, 预测=正常
样本2: 欺诈概率=0.0196, 预测=正常
样本3: 欺诈概率=0.1245, 预测=正常
样本4: 欺诈概率=0.0199, 预测=正常
样本5: 欺诈概率=0.0307, 预测=正常

样本1: 欺诈概率=0.0311, 预测=正常
样本2: 欺诈概率=0.0210, 预测=正常
样本3: 欺诈概率=0.1211, 预测=正常
样本4: 欺诈概率=0.0234, 预测=正常
样本5: 欺诈概率=0.0284, 预测=正常

## 6. 总结

本Notebook演示了完整的 **PySpark + XGBoost 分布式机器学习流程**：

| 步骤 | 内容 | 分布式特性 |
|------|------|------------|
| 数据加载 | CSV → Spark DataFrame | 数据自动分区到多worker |
| 数据探索 | 描述性统计、类别分布 | 各worker并行计算聚合 |
| 特征工程 | VectorAssembler | 无需标准化（树模型） |
| 训练/测试划分 | randomSplit | 分布式shuffle |
| 模型训练 | SparkXGBClassifier | 多worker并行训练XGBoost |
| 模型评估 | AUC、PR-AUC、F1、混淆矩阵 | 分布式预测+聚合 |
| 新数据预测 | VectorAssembler + XGBoost | 分布式推理 |

In [12]:
# spark.stop()  # 取消注释以释放资源